Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2019-11, with the labels that each got.

#227 Cherry pick hashicorp/terraform#22597: Ensure for_each values wholly known for sets
  terraform/context_apply_test.go
  terraform/context_plan_test.go
  terraform/eval_for_each.go
  terraform/node_data_refresh.go
  terraform/terraform_test.go
  terraform/testdata/plan-for-each-unknown-value/main.tf
Labels: core-cherry-pick

#228 Cherry-pick hashicorp/terraform #23063
  go.mod
  go.sum
  internal/configs/configload/loader.go
  internal/configs/configload/module_mgr.go
  internal/plugin/discovery/get.go
  internal/plugin/discovery/get_test.go
  internal/registry/client.go
  internal/registry/client_test.go
  internal/registry/errors.go
  internal/registry/regsrc/friendly_host.go
  internal/registry/regsrc/module.go
  internal/registry/regsrc/terraform_provider.go
  internal/registry/test/mock_registry.go
  internal/svchost/auth/cache.go
  internal/svchost/auth/credentials.go
  internal/svchost/auth/from_map.go
  internal/svchost/auth/helper_program.go
  internal/svchost/auth/helper_program_test.go
  internal/svchost/auth/static.go
  internal/svchost/auth/static_test.go
  internal/svchost/auth/testdata/.gitignore
  internal/svchost/auth/testdata/main.go
  internal/svchost/auth/testdata/test-helper
  internal/svchost/auth/token_credentials.go
  internal/svchost/auth/token_credentials_test.go
  internal/svchost/disco/disco.go
  internal/svchost/disco/disco_test.go
  internal/svchost/disco/host.go
  internal/svchost/disco/host_test.go
  internal/svchost/label_iter.go
  internal/svchost/svchost.go
  internal/svchost/svchost_test.go
Labels: core-cherry-pick

#219 Cherrypick hashicorp/terraform#22937
  terraform/context_apply_test.go
  terraform/graph_builder_apply.go
  terraform/graph_builder_apply_test.go
  terraform/testdata/apply-destroy-data-cycle/main.tf
  terraform/testdata/apply-module-replace-cycle-cbd/main.tf
  terraform/testdata/apply-module-replace-cycle-cbd/mod1/main.tf
  terraform/testdata/apply-module-replace-cycle-cbd/mod2/main.tf
  terraform/testdata/apply-module-replace-cycle/main.tf
  terraform/testdata/apply-module-replace-cycle/mod1/main.tf
  terraform/testdata/apply-module-replace-cycle/mod2/main.tf
  terraform/testdata/transform-cbd-destroy-edge-both-count/main.tf
  terraform/testdata/transform-cbd-destroy-edge-count/main.tf
  terraform/testdata/transform-destroy-cbd-edge-basic/main.tf
  terraform/transform_config_flat.go
  terraform/transform_config_flat_test.go
  terraform/transform_destroy_cbd.go
  terraform/transform_destroy_cbd_test.go
  terraform/transform_destroy_edge.go
  terraform/transform_diff.go
Labels: core-cherry-pick

#225 Feature: `AtLeastOneOf` and `ExactlyOneOf` validation flags added to schema
  CHANGELOG.md
  helper/schema/schema.go
  helper/schema/schema_test.go
Labels: enhancement

#212 Add 'StringDoesNotContainAny' validation function
  helper/validation/validation.go
  helper/validation/validation_test.go
Labels: enhancement

#252 deps: Update github.com/hashicorp/terraform-config-inspect@17f92b0546e8602e4cecb14d2263f0b1746b9cc9
  go.mod
  go.sum
Labels: technical-debt
