Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2020-04, with the labels that each got.

#374 Remove unnecessary comment
  helper/schema/resource.go
Labels: documentation

#400 upgrade to terraform-plugin-test@v1.3.0
  go.mod
  go.sum
Labels: port-to-v2

#396 Make mockT.Fatal halt execution
  helper/resource/testing.go
  helper/resource/testing_test.go
Labels: port-to-v2

#304 Add various Map key and value validators
  helper/validation/map.go
  helper/validation/map_test.go
Labels: enhancement

#405 Port provider_meta functionality from core.
  helper/schema/provider.go
  helper/schema/resource.go
  helper/schema/resource_data.go
  internal/helper/plugin/grpc_provider.go
  terraform/state.go
Labels: core-cherry-pick, enhancement, protocol-5-only

#364 tests/helper/schema: Add unit testing covering existing behavior of ConflictsWith and list index/map key syntax
  helper/schema/schema_test.go
Labels: enhancement

#415 fix acctest docs
  acctest/doc.go
Labels: port-to-v2

#419 privatize RunNewTest
  helper/resource/testing.go
  helper/resource/testing_new.go
Labels: breaking-change

#414 Remove Removed and prune related code
  helper/resource/testing_new_import_state.go
  helper/schema/field_reader.go
  helper/schema/resource.go
  helper/schema/schema.go
  helper/schema/schema_test.go
  internal/addrs/module_instance.go
  internal/addrs/provider_config.go
  internal/addrs/provider_config_test.go
  internal/addrs/referenceable.go
  internal/addrs/resource.go
  internal/addrs/resource_phase.go
  internal/addrs/targetable.go
  internal/helper/plugin/grpc_provider.go
  internal/helper/plugin/grpc_provider_test.go
  terraform/state.go
Labels: breaking-change

#418 helper/schema: Allow self references with AllowOneOf, ExactlyOneOf, and RequiredWith in InternalValidate
  helper/schema/schema.go
  helper/schema/schema_test.go
Labels: port-to-v1
