Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2020-05, with the labels that each got.

#436 Remove helper/encryption package.
  helper/encryption/encryption.go
Labels: breaking-change

#448 fix meta.SDKPrerelease parsing
  scripts/release/release.sh
Labels: port-to-v1

#465 helper/schema: Support serialization of bool values in TypeMap values [v1]
  helper/schema/serialize.go
  helper/schema/serialize_test.go
Labels: port-to-v2
