Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2020-01, with the labels that each got.

#287 schema/ExactlyOneOf: Fix handling of unknowns in complex types
  helper/schema/schema.go
  helper/schema/schema_test.go
Labels: bug

#288 Fix typo in Readme
  README.md
Labels: documentation

#292 Changes log level for missing dependent sweepers
  helper/resource/testing.go
Labels: testing
