Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2021-04, with the labels that each got.

#748 [v1] Stop using json.Number when decoding Private.
  internal/helper/plugin/grpc_provider.go
Labels: bug, v1-maint

#749 Link to v1-maint support policy.
  SUPPORT.md
Labels: documentation

#755 helper/schema: Adjusted validation error messages
  helper/schema/schema.go
  helper/schema/schema_test.go
Labels: enhancement, ui
