Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2022-04, with the labels that each got.

#934 Bump Expected Minimum Go Version to 1.17
  .changelog/934.txt
  .github/workflows/ci-go.yml
  .go-version
  .golangci.yml
  README.md
  go.mod
  helper/schema/schema_test.go
Labels: enhancement

#936 helper/schema: Prevent missing SDK logging entries and confusing provider.stdio TRACE entries
  .changelog/936.txt
  internal/logging/context.go
  internal/logging/environment_variables.go
Labels: bug

#925 Improve "unsupported test mode" message
  helper/resource/testing_new.go
Labels: subsystem/tests

#940 all: Replace various log.Printf calls with tfsdklog calls
  helper/resource/plugin.go
  helper/schema/grpc_provider.go
  helper/schema/provider.go
  helper/schema/resource.go
  helper/schema/resource_diff_test.go
  helper/schema/schema.go
  internal/logging/helper_schema.go
  internal/plugin/convert/schema.go
  internal/plugin/convert/schema_test.go
Labels: bug

#938 helper/resource: Ensure Terraform CLI logs are written to `TF_LOG_PATH_MASK` environment variable value when both `TF_ACC_LOG_PATH` and `TF_LOG_PATH_MASK` are set
  .changelog/938.txt
  internal/logging/keys.go
  internal/plugintest/environment_variables.go
  internal/plugintest/guard.go
  internal/plugintest/helper.go
  internal/plugintest/working_dir.go
Labels: bug

#939 internal/logging: Ensure `@caller` in SDK subsystem logging entries accurately reflects calling code location
  .changelog/939.txt
  internal/logging/context.go
Labels: bug

#950 Adding `resource.TestCheckResourceAttrWith` test utility
  .changelog/950.txt
  helper/resource/testing.go
  helper/resource/testing_example_test.go
  helper/resource/testing_test.go
Labels: enhancement, subsystem/tests
