Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2022-08, with the labels that each got.

#1027 all: Bump Go Version to 1.18
  .changelog/1027.txt
  .github/workflows/ci-go.yml
  README.md
  go.mod
  go.sum
  helper/schema/provider_go115_test.go
  helper/schema/provider_prego115_test.go
  helper/schema/provider_test.go
  website/docs/plugin/sdkv2/testing/acceptance-tests/index.mdx
Labels: technical-debt

#1028 helper/schema: Clarify Schema type Deprecated documentation for Terraform 1.2.7 and later
  helper/schema/schema.go
  website/docs/plugin/sdkv2/schemas/schema-methods.mdx
Labels: documentation

#1029 website: Replace interface{} with any
  website/docs/plugin/sdkv2/best-practices/deprecations.mdx
  website/docs/plugin/sdkv2/best-practices/detecting-drift.mdx
  website/docs/plugin/sdkv2/guides/terraform-0.12-compatibility.mdx
  website/docs/plugin/sdkv2/guides/v2-upgrade-guide.mdx
  website/docs/plugin/sdkv2/logging/http-transport.mdx
  website/docs/plugin/sdkv2/resources/customizing-differences.mdx
  website/docs/plugin/sdkv2/resources/import.mdx
  website/docs/plugin/sdkv2/resources/retries-and-customizable-timeouts.mdx
  website/docs/plugin/sdkv2/resources/state-migration.mdx
  website/docs/plugin/sdkv2/schemas/schema-behaviors.mdx
  website/docs/plugin/sdkv2/schemas/schema-methods.mdx
  website/docs/plugin/sdkv2/schemas/schema-types.mdx
  website/docs/plugin/sdkv2/testing/acceptance-tests/sweepers.mdx
Labels: documentation, technical-debt

#1031 Modifying underlying logic behind `TestStep.Taint` to call the `terrafom taint` command
  .changelog/1031.txt
  helper/resource/testing_config.go
  helper/resource/testing_new.go
  helper/resource/teststep_providers_test.go
  internal/plugintest/working_dir.go
  terraform/state.go
  terraform/state_test.go
Labels: enhancement

#1024 helper/schema: Ensure InstanceDiff RawConfig/RawPlan/RawState are always copied during planning
  .changelog/1024.txt
  helper/schema/schema.go
Labels: bug

#1037 Update naming.mdx
  website/docs/plugin/sdkv2/best-practices/naming.mdx
Labels: documentation

#969 Fix panic message to show correct unhandled type rather than the parent type
  helper/schema/schema.go
Labels: bug

#1022 docs: customdiff.{ValidateChange,ForceNewIfChange,ComputedIf} take a context.Context
  helper/customdiff/compose.go
  website/docs/plugin/sdkv2/resources/customizing-differences.mdx
Labels: documentation

#826 fix: add path to error when list has too many or few items
  helper/schema/schema.go
  helper/schema/schema_test.go
Labels: bug
