Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2022-07, with the labels that each got.

#993 helper/resource: Add `TF_ACC_LOG`, `TF_LOG_CORE`, and `TF_LOG_PROVIDER` environment variable handling for Terraform versions 0.15 and later
  .changelog/993.txt
  internal/logging/keys.go
  internal/plugintest/environment_variables.go
  internal/plugintest/helper.go
  website/docs/plugin/sdkv2/testing/acceptance-tests/index.mdx
Labels: enhancement, subsystem/tests

#997 website: Documentation for parallel logging issues with TF_LOG_PATH_MASK
  website/docs/plugin/sdkv2/testing/acceptance-tests/index.mdx
Labels: documentation, subsystem/tests

#1006 Introduce `NewLoggingHTTPTransport` and deprecate `NewTransport`
  .changelog/1006.txt
  .github/workflows/ci-go.yml
  .gitignore
  Makefile
  go.mod
  go.sum
  helper/logging/logging_http_transport.go
  helper/logging/logging_http_transport_test.go
  helper/logging/transport.go
  helper/schema/provider_test.go
Labels: enhancement, subsystem/observability

#1013 helper/schema: Clarify Schema type Deprecated field usage
  helper/schema/schema.go
  website/docs/plugin/sdkv2/schemas/schema-methods.mdx
Labels: documentation

#1016 website: Logging navigation adjustments, minor HTTP Transport page fixes
  website/data/plugin-sdk-nav-data.json
  website/docs/plugin/sdkv2/logging/http-transport.mdx
Labels: documentation
