Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2022-01, with the labels that each got.

#840 Fix a tiny typo in the time helper docs
  helper/validation/time.go
Labels: documentation, waiting-response

#842 Enable dependabot
  .github/dependabot.yml
Labels: technical-debt

#626 Adds HasChanges() to ResourceDiff
  helper/schema/resource_diff.go
  helper/schema/resource_diff_test.go
  helper/schema/schema.go
Labels: enhancement

#862 deps: Remove github.com/golang/mock and github.com/go-test/deep
  go.mod
  go.sum
  helper/resource/testing_new_test.go
  internal/configs/hcl2shim/flatmap_test.go
  tools/tools.go
Labels: technical-debt, dependencies

#860 Update Contributing Guide with unit testing information
  .github/CONTRIBUTING.md
Labels: documentation

#867 add docs on why old might be empty in diffsuppressfunc
  helper/schema/schema.go
Labels: documentation
