Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2022-09, with the labels that each got.

#1045 helper/logging: Update test Content-Type header to match terraform.io change
  helper/logging/logging_http_transport_test.go
Labels: technical-debt

#1047 schema: fix unknown value validation bug
  helper/schema/schema.go
  helper/schema/schema_test.go
Labels: bug

#1052 Use ImportStatePersist to preserve state generated by import operation
  .changelog/1052.txt
  helper/resource/testing.go
  helper/resource/testing_new_import_state.go
  helper/resource/teststep_providers_test.go
Labels: enhancement, subsystem/tests

#1057 helper/resource: Prevent `Inconsistent dependency lock file` errors when using `ExternalProviders` outside the `hashicorp` namespace
  .changelog/1057.txt
  helper/resource/testcase_providers_test.go
  helper/resource/testing_new.go
  helper/resource/testing_new_config.go
  helper/resource/teststep_providers.go
  helper/resource/teststep_providers_test.go
Labels: bug, subsystem/tests

#1056 internal/plugintest: Switch from (os.File).Readdir() to os.ReadDir()
  internal/plugintest/util.go
Labels: technical-debt

#1058 helper/resource: Add `terraform plan` output to `TRACE` logging
  .changelog/1058.txt
  internal/logging/keys.go
  internal/plugintest/working_dir.go
Labels: enhancement, subsystem/tests

#1059 helper/resource: Add Terraform configuration to `TRACE` logging
  .changelog/1059.txt
  internal/logging/keys.go
  internal/plugintest/working_dir.go
Labels: enhancement, subsystem/tests
