Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2022-03, with the labels that each got.

#892 helper/resource: Only call final Terraform CLI show command each TestStep when TestCase.IDRefreshName is set
  .changelog/892.txt
  helper/resource/testing.go
  helper/resource/testing_new_config.go
Labels: bug, documentation

#905 plugin: Always forward tf6server close channel
  .github/workflows/ci-go.yml
  helper/resource/plugin.go
  helper/resource/testing_new.go
  internal/logging/keys.go
  internal/plugintest/working_dir.go
  plugin/serve.go
Labels: bug

#722 Support testing of configurations in JSON syntax.
  helper/resource/testing.go
  internal/plugintest/working_dir.go
  internal/plugintest/working_dir_json_test.go
Labels: enhancement, subsystem/tests

#912 helper/schema: Additional Go documentation for Resource and Schema types
  helper/schema/resource.go
  helper/schema/schema.go
Labels: documentation

#911 helper/resource: Additional Go documentation for TestCheck and TestMatch functions
  helper/resource/testing.go
  helper/resource/testing_example_test.go
Labels: documentation

#841 helper/schema: Make int fields accept string values from DefaultFunc().
  helper/schema/schema.go
  helper/schema/schema_test.go
Labels: bug

#913 internal/plugintest: Set CHECKPOINT_DISABLE=1 in terraform-exec directly
  .changelog/913.txt
  helper/resource/plugin.go
  internal/plugintest/environment_variables.go
  internal/plugintest/helper.go
  internal/plugintest/working_dir.go
Labels: technical-debt, subsystem/tests

#915 helper/validation: Prevented panics with `ToDiagFunc()` function when used inside `Schema` type `Elem` field
  .changelog/915.txt
  helper/validation/meta.go
  helper/validation/meta_test.go
  helper/validation/testing.go
Labels: bug, subsystem/diagnostics

#914 helper/schema: Prevented panics during error to diagnostic conversion
  .changelog/914.txt
  helper/schema/grpc_provider.go
  helper/schema/grpc_provider_test.go
  internal/plugin/convert/diagnostics.go
Labels: bug, subsystem/diagnostics

#916 helper/resource: Additional Go documentation for TypeSet TestCheckFunc
  helper/resource/testing_sets.go
  helper/resource/testing_sets_example_test.go
Labels: documentation

#921 helper/schema: Update Go documentation for StateUpgradeFunc
  helper/schema/resource.go
Labels: documentation

#920 helper/resource: Added error when errantly checking list, map, or set attributes in `TestCheckNoResourceAttr`, `TestCheckResourceAttr`, and `TestCheckResourceAttrSet`
  .changelog/920.txt
  helper/resource/testing.go
  helper/resource/testing_test.go
Labels: enhancement, subsystem/tests
