Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2022-11, with the labels that each got.

#1087 update StateMigrator Docs v0.12 code block
  website/docs/plugin/sdkv2/resources/state-migration.mdx
Labels: documentation

#1089 helper/resource: Skip data source states with TestStep.ImportStateCheck
  .changelog/1089.txt
  helper/resource/testing.go
  helper/resource/testing_new_import_state.go
  helper/resource/testing_new_import_state_test.go
Labels: bug, subsystem/tests

#1090 all: Remove deprecated io/ioutil package usage
  helper/logging/logging.go
  helper/resource/plugin.go
  internal/plugintest/config.go
  internal/plugintest/helper.go
  internal/plugintest/working_dir.go
Labels: technical-debt

#1091 helper/resource: Various small fixes
  .changelog/1091.txt
  helper/resource/plugin.go
  helper/resource/plugin_test.go
  internal/plugintest/working_dir.go
Labels: bug, subsystem/tests

#1098 Linking to the framework migration guide
  website/data/plugin-sdk-nav-data.json
  website/docs/plugin/sdkv2/index.mdx
Labels: documentation

#1092 helper/resource: Check for existing provider configuration block in TestStep merged configuration
  .changelog/1092.txt
  helper/resource/testcase_providers.go
  helper/resource/testcase_providers_test.go
  helper/resource/testing_new.go
  helper/resource/teststep_providers.go
  helper/resource/teststep_providers_test.go
Labels: bug, subsystem/tests

#1105 internal: Prune wholly unused code
  internal/addrs/resource.go
  internal/addrs/resourcemode_string.go
  internal/tfdiags/diagnostics.go
  internal/tfdiags/rpc_friendly.go
  internal/tfdiags/rpc_friendly_test.go
Labels: technical-debt

#1093 Replace deprecated golangci-lint linters deadcode and varcheck with unused
  .golangci.yml
  internal/plugintest/working_dir.go
Labels: technical-debt

#1106 deps: Remove golang.org/x/tools dependency
  go.mod
  go.sum
  helper/schema/resource_data_get_source.go
  helper/schema/valuetype.go
  internal/configs/configschema/schema.go
  internal/tfdiags/diagnostic.go
  terraform/instancetype.go
  terraform/resource_mode.go
  tools/tools.go
Labels: technical-debt

#1107 deps: Remove github.com/apparentlymart/go-dump and github.com/davecgh/go-spew
  go.mod
  go.sum
  helper/resource/testing_new.go
  helper/resource/testing_new_import_state.go
  helper/resource/testing_new_import_state_test.go
  helper/resource/testing_new_refresh_state.go
  helper/schema/resource_diff_test.go
  internal/configs/configschema/coerce_value_test.go
  internal/configs/configschema/empty_value_test.go
  internal/plans/objchange/normalize_obj_test.go
  terraform/state_test.go
Labels: technical-debt, dependencies

#1108 deps: Update golang.org/x/crypto@v0.3.0
  go.mod
  go.sum
  helper/acctest/random.go
  helper/acctest/random_test.go
Labels: technical-debt, dependencies

#1110 deps: Remove github.com/apparentlymart/go-cidr
  go.mod
  go.sum
  helper/acctest/random.go
  helper/acctest/random_test.go
Labels: technical-debt
