Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2023-03, with the labels that each got.

#1163 Updating to Go 1.19
  .changes/unreleased/NOTES-20230303-111728.yaml
  .github/workflows/ci-go.yml
  README.md
  go.mod
  website/docs/plugin/sdkv2/testing/acceptance-tests/index.mdx
Labels: dependencies, go

#1164 helper/acctest: Further document RandTLSCert characteristics
  helper/acctest/random.go
Labels: documentation

#1167 Fix migration to terraform-plugin-testing causes panic in existing test suite
  .changes/unreleased/ENHANCEMENTS-20230310-132324.yaml
  .changes/unreleased/ENHANCEMENTS-20230310-132539.yaml
  .changes/unreleased/NOTES-20230310-131553.yaml
  .changes/unreleased/NOTES-20230310-131709.yaml
  helper/id/id.go
  helper/id/id_test.go
  helper/resource/aliases.go
  helper/resource/testcase_providers_test.go
  helper/retry/error.go
  helper/retry/state.go
  helper/retry/state_test.go
  helper/retry/wait.go
  helper/retry/wait_test.go
  website/docs/plugin/sdkv2/guides/v2-upgrade-guide.mdx
  website/docs/plugin/sdkv2/resources/retries-and-customizable-timeouts.mdx
Labels: bug

#1170 Removed non-sdk best practice documentation
  .github/CONTRIBUTING.md
  website/data/plugin-sdkv2-nav-data.json
  website/docs/plugin/sdkv2/best-practices/depending-on-providers.mdx
  website/docs/plugin/sdkv2/best-practices/deprecations.mdx
  website/docs/plugin/sdkv2/best-practices/detecting-drift.mdx
  website/docs/plugin/sdkv2/best-practices/index.mdx
  website/docs/plugin/sdkv2/best-practices/naming.mdx
  website/docs/plugin/sdkv2/best-practices/other-languages.mdx
  website/docs/plugin/sdkv2/best-practices/sensitive-state.mdx
  website/docs/plugin/sdkv2/best-practices/testing.mdx
  website/docs/plugin/sdkv2/best-practices/versioning.mdx
  website/docs/plugin/sdkv2/guides/v2-upgrade-guide.mdx
  website/docs/plugin/sdkv2/resources/import.mdx
Labels: documentation

#1177 helper/resource: Add missing equals for type aliases
  .changes/unreleased/BUG FIXES-20230321-085655.yaml
  helper/resource/aliases.go
Labels: bug
