Repository hashicorp/terraform-plugin-sdk, pull requests merged in 2025-02, with the labels that each got.

#1421 chore: Update CI to run corner tests on all v5 protocol Terraform versions
  .github/workflows/ci-go.yml
Labels: github_actions

#1428 chore: Update golangci-lint linters and apply fixes
  .golangci.yml
  helper/acctest/random_test.go
  helper/resource/plugin_test.go
  helper/resource/testcase_providers_test.go
  helper/resource/testcase_validate_test.go
  helper/resource/testing_test.go
  helper/resource/teststep_providers_test.go
  helper/resource/teststep_validate_test.go
  helper/schema/grpc_provider_test.go
  helper/schema/provider_test.go
  helper/structure/suppress_json_diff_test.go
  helper/validation/meta_test.go
  internal/configs/hcl2shim/flatmap_test.go
  internal/plugin/convert/diagnostics.go
Labels: technical-debt

#1427 helper/schema: Add validation to prevent write-only attributes in set nested blocks
  .changes/unreleased/BUG FIXES-20250218-172440.yaml
  .changes/unreleased/NOTES-20250218-172625.yaml
  helper/schema/schema.go
  helper/schema/schema_test.go
  website/docs/plugin/sdkv2/resources/write-only-arguments.mdx
  website/docs/plugin/sdkv2/schemas/schema-behaviors.mdx
Labels: bug
